config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions] 

  as :user do
    post '/users/sign_in' => 'devise/sessions#create', as: :user_session
    delete '/users/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
    get '/users/sign_out' => 'devise/sessions#destroy', as: :get_destroy_user_session
  end

  authenticated :user do
    resources :projects, only: [:index, :new, :create, :show, :destroy, :update] do
      resources :sections, only: [:new, :create, :destroy, :update] do
        resources :todos, only: [:new, :create, :update, :destroy]
        resources :links, only: [:new, :create, :destroy], controller: 'snippets'
      end
    end

    resources :goals, only: [:new, :create, :destroy, :update] do
      member do
        post :complete
      end
    end

    resources :life_areas, only: [:update]

    resources :why_statements, only: [:update]

    get '/life-plan', controller: 'life_plan', action: 'index' do
    end

    get '/media' => 'media#index', as: :media

    resources :links, only: [:new, :create, :destroy]

    root to: 'welcome#main', as: :main
    get '/export' => 'shipping#export', as: :export
  end

  unauthenticated do
    root to: 'welcome#index'
    get '*path' => redirect('/')
  end
end

app/controllers/life_plan_controller.rb
class LifePlanController < ApplicationController
  def index
    @why = WhyStatement.first_or_create

    @life_areas = LifeArea.all.order(:name)

    @goals = current_user.goals.includes(:term, :life_area).where(completed: false)
    @goals = @goals.group_by { |goal| goal.term }
    @goals.each_pair { |term, goal_array| goal_array.sort_by! { |goal| goal.life_area.name } }
    @goals = @goals.sort_by { |term, goals| term.days }.reverse!
  end
end

app/views/life_plan/index.haml
= javascript_include_tag 'jquery.simulate.drag-sortable.js' if Rails.env.test?
#life-plan.contentpane
  %ul.accordion-tabs-minimal
    %li.tab-header-and-content
      %a#visions-tab.tab-link.is-active{:href => "#"} Visions
      .tab-content
        .container
          %h2
            To
            %span.contribution= best_in_place @why, :contribution, place_holder: '<span class="empty">(contribution)</span>'
            %br
            so that
            %span.impact= best_in_place @why, :impact, place_holder: '<span class="empty">(impact)</span>'

          - @life_areas.each do |life_area|
            .vision_container{id: "vision_#{life_area.name}"}
              %h2.life-area
                %i.fa{class: "#{life_area.icon}"}
                = life_area.name.titleize
              .identity= best_in_place life_area, :identity, place_holder: '<span class="empty">(identity)</span>'
              .vision= best_in_place life_area, :vision, place_holder: '<span class="empty">(vision)</span>'
              .purpose= best_in_place life_area, :purpose, place_holder: '<span class="empty">(purpose)</span>'
    %li.tab-header-and-content
      %a#goals-tab.tab-link{:href => "#"} Goals
      .tab-content
        .container
          - @goals.each do |term, goals|
            %h2.term{class: term.name}= term.name
            %ol
              - goals.each do |goal|
                %li.goal{id: "goal_#{goal.id}"}
                  %i.goal-icon.fa{class: "#{goal.life_area.icon}"}
                  = best_in_place goal, :description
                  = link_to goal_path(goal), method: :delete, id: "goal_#{goal.id}", class: 'delete-goal-link' do
                    %i.fa.fa-close
                  = link_to complete_goal_path(goal), method: :post, id: "goal_#{goal.id}_complete", class: 'complete-goal-link' do
                    %i.fa.fa-check-circle-o
          = link_to new_goal_path, id: 'create-goal-link' do
            %button Add