config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions] 

  as :user do
    post '/users/sign_in' => 'devise/sessions#create', as: :user_session
    delete '/users/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
    get '/users/sign_out' => 'devise/sessions#destroy', as: :get_destroy_user_session
  end

  authenticated :user do
    resources :projects, only: [:index, :new, :create, :show, :destroy, :update] do
      resources :sections, only: [:new, :create, :destroy, :update] do
        resources :todos, only: [:new, :create, :update, :destroy]
        resources :links, only: [:new, :create, :destroy], controller: 'snippets'
      end
    end

    resources :goals, only: [:new, :create, :destroy, :update] do
      member do
        post :complete
      end
    end

    resources :life_areas, only: [:update]

    resources :why_statements, only: [:update]

    get '/life-plan', controller: 'life_plan', action: 'index' do
    end

    get '/media' => 'media#index', as: :media

    resources :links, only: [:new, :create, :destroy]

    root to: 'welcome#main', as: :main
    get '/export' => 'shipping#export', as: :export
  end

  unauthenticated do
    root to: 'welcome#index'
    get '*path' => redirect('/')
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :sections, dependent: :destroy

  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :json

  before_filter :load_project, only: [:show, :destroy, :update]

  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def create
    respond_with current_user.projects.create(params.require(:project).permit([:name, :description]))
  end

  def show
  end

  def destroy
    @project.try(:destroy)

    respond_with @project
  end

  def update
    @project.update_attributes(params.require(:project).permit(:name, :description))
    respond_with @project
  end

  private

  def load_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_links.haml
.links
  - section.links.each do |snippet|
    .link
      .title= link_to snippet.title, url_with_protocol(snippet.url), target: '_blank'
      .excerpt= snippet.excerpt
      = link_to project_section_link_path(@project, section, snippet), name: 'delete-link', method: 'delete' do
        %i.fa.fa-close
#add-link-link 
  = link_to new_project_section_link_path(@project, section) do
    %i.fa.fa-plus
    Add

app/views/projects/_todos.haml
.todos
  - section.todos.each do |todo|
    .todo{id: "todo_#{todo.id}"}
      = best_in_place todo, :completed, as: :checkbox, url: project_section_todo_path(@project, section, todo), collection: {'false' => raw("<i class='fa fa-square-o'></i>"), 'true' => raw("<i class='fa fa-check-square-o'></i>")}, place_holder: raw("<i class='fa fa-square-o'></i>")
      %span.description= best_in_place [@project, section, todo], :description
#add-todo-link
  = link_to new_project_section_todo_path(@project, section) do
    %i.fa.fa-plus
    Add

app/views/projects/index.haml
#projects.contentpane
  .container
    - @projects.each do |project|
      .project
        = link_to project_path(project) do
          .name= project.name
        = link_to project_path(project), method: :delete do
          %i.fa.fa-close
        = link_to project_path(project) do
          .description= project.description
    = link_to new_project_path, id: 'create-project-link', class: 'project' do
      .name Create A New Project
      .description +

app/views/projects/new.haml
#create-project.contentpane
  = form_for @project do |f|
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :description
      = f.text_field :description
    = f.submit 'Create'

app/views/projects/show.haml
#show-project.contentpane
  %h1= best_in_place @project, :name
  .description= best_in_place @project, :description

  - @project.sections.each do |section|
    %h2.section{id: "section#{section.id}"}
      = best_in_place [@project, section], :name
      = link_to project_section_path(@project, section), name: 'delete-link', method: 'delete' do
        %i.fa.fa-close
    = render partial: section.section_type, locals: {project: @project, section: section}

  #add-section-link
    = link_to new_project_section_path(@project) do
      %i.fa.fa-plus
      Add Section